[build]
  publish = "PM"

[[edge_functions]]
  function = "auth-guard"
  path = "/adherents/*"

[[edge_functions]]
  function = "auth-guard"
  path = "/adherents"

[[edge_functions]]
  function = "auth-guard"
  path = "/adherents/index.html"

[[redirects]]
  from = "/login"
  to   = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/callback"
  to   = "/.netlify/functions/callback"
  status = 200

[[redirects]]
  from = "/logout"
  to   = "/.netlify/functions/logout"
  status = 200
