[build]
  # Remplace "PM" par le dossier où se trouve ton site (index.html, etc.)
  publish = "PM"

[functions]
  node_bundler = "esbuild"

# Protéger toutes les pages /adherents/* via une Edge Function
[[edge_functions]]
  function = "auth-guard"
  path = "/adherents/*"

# Raccourcis vers les fonctions de login/callback
[[redirects]]
  from = "/login"
  to   = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/callback"
  to   = "/.netlify/functions/callback"
  status = 200
